-- 코드를 작성해주세요
SELECT ed1.ID AS ID, COALESCE(COUNT(ed2.PARENT_ID),0) AS CHILD_COUNT FROM ECOLI_DATA ed1
LEFT JOIN ECOLI_DATA ed2
ON ed1.ID =ed2.PARENT_ID
GROUP BY ed1.ID
ORDER BY ed1.ID



# SELECT PARENT.ID, COALESCE(COUNT(CHILD.PARENT_ID),0) AS CHILD_COUNT
# FROM ECOLI_DATA AS PARENT 
# LEFT JOIN ECOLI_DATA AS CHILD
# ON PARENT.ID = CHILD.PARENT_ID
# GROUP BY PARENT.ID
# ORDER BY PARENT.ID;