-- 코드를 입력하세요
SELECT 
DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
FROM ONLINE_SALE
where Month(SALES_DATE) = 3

union

SELECT 
DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
PRODUCT_ID,
NULL as USER_ID,
SALES_AMOUNT
FROM OFFLINE_SALE
where Month(SALES_DATE) = 3

order by SALES_DATE,PRODUCT_ID, USER_ID