SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS, -- DISTINCT 추가
    ROUND(
        COUNT(DISTINCT os.USER_ID) / 
        (SELECT COUNT(DISTINCT ui.USER_ID) FROM USER_INFO ui WHERE YEAR(ui.JOINED) = 2021), 
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE os
WHERE os.USER_ID IN (
    SELECT DISTINCT ui.USER_ID FROM USER_INFO ui
    WHERE YEAR(ui.JOINED) = 2021
) 
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;