-- 코드를 입력하세요
SELECT gu.USER_ID, gu.NICKNAME, sum(gb.PRICE) as TOTAL_SALES 
FROM USED_GOODS_BOARD as gb
INNER JOIN  USED_GOODS_USER as gu ON gu.USER_ID = gb.WRITER_ID
WHERE gb.STATUS = 'DONE'
GROUP BY gu.USER_ID
HAVING TOTAL_SALES >= 700000 
ORDER BY TOTAL_SALES
