SELECT he.EMP_NO,he.EMP_NAME,
CASE
    WHEN hr.SCORE >=96 THEN 'S'
    WHEN hr.SCORE >=90 THEN 'A'
    WHEN hr.SCORE >= 80 THEN 'B'
    ELSE 'C'
END as GRADE,
CASE
    WHEN hr.SCORE >=96 THEN he.SAL * 0.2
    WHEN hr.SCORE >=90 THEN he.SAL * 0.15
    WHEN hr.SCORE >= 80 THEN he.SAL * 0.1
    ELSE 0
END as BONUS
FROM HR_EMPLOYEES he
LEFT JOIN (SELECT hr.EMP_NO,avg(hr.SCORE) as SCORE FROM HR_GRADE hr
GROUP BY EMP_NO) hr ON he.EMP_NO = hr.EMP_NO
ORDER BY he.EMP_NO ASC


