-- 코드를 작성해주세요
SELECT ed.ID, ed.GENOTYPE, ped.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA as ed
LEFT JOIN ECOLI_DATA as ped ON ed.PARENT_ID = ped.ID
WHERE ed.GENOTYPE & ped.GENOTYPE = ped.GENOTYPE
ORDER BY ed.ID