-- 코드를 작성해주세요

SELECT 
    EC_YEAR_DATA.year as YEAR, 
    max_data - ed.SIZE_OF_COLONY as YEAR_DEV,
    ed.ID
FROM ECOLI_DATA ed
JOIN (
    SELECT year(DIFFERENTIATION_DATE) as year,MAX(SIZE_OF_COLONY) as max_data FROM ECOLI_DATA
GROUP BY year(DIFFERENTIATION_DATE)
) EC_YEAR_DATA ON  year(ed.DIFFERENTIATION_DATE) = EC_YEAR_DATA.year
ORDER BY YEAR ASC ,YEAR_DEV ASC


