-- 코드를 작성해주세요
SELECT sg.SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL 
FROM HR_EMPLOYEES he
LEFT JOIN (
    SELECT hr.EMP_NO, SUM(hr.SCORE) AS SCORE 
    FROM HR_GRADE hr
    GROUP BY hr.EMP_NO
) sg ON he.EMP_NO = sg.EMP_NO 
LEFT JOIN HR_DEPARTMENT hd ON hd.DEPT_ID = he.DEPT_ID
ORDER BY sg.SCORE DESC
limit 1;