-- 코드를 작성해주세요
SELECT hd.DEPT_ID,hd.DEPT_NAME_EN, ROUND(AVG(he.SAL)) as AVG_SAL
FROM HR_EMPLOYEES he  
LEFT JOIN HR_DEPARTMENT hd  ON he.DEPT_ID = hd.DEPT_ID
GROUP BY hd.DEPT_ID
ORDER BY AVG_SAL DESC

