-- 코드를 입력하세요
SELECT CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK as b
INNER JOIN BOOK_SALES  as bs ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY